workspace:
  base: /go
  path: src/github.com/uswitch/es-metrics

pipeline:
  build:
    when:
      event: [ push, pull_request ]
    image: golang:1.9
    commands:
      - go test -v ./...
      - CGO_ENABLED=0 go build -o bin/ls-metrics .

  publish:
    when:
      event: push
      branch: master
    image: plugins/docker
    repo: registry.usw.co/cloud/ls-metrics
    tags:
      - latest
      - stable
      - "${DRONE_COMMIT}"
